version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: IMS_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Internship-Management-System
    ports:
      - "3306:3306"
    volumes:
      - backend-ims_db_app_ims:/var/lib/mysql
    networks:
      - backend-ims_ims-network

  app:
    image: wajdiraouafi/backend-ims
    container_name: IMS_backend
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Internship-Management-System?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend-ims_ims-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend-ims_ims-network
    
  frontend:
    image: wajdiraouafi/frontend-ims
    container_name: IMS_frontend
    ports:
      - "4200:4200"
    depends_on:
      - app
    networks:
      - backend-ims_ims-network

networks:
  backend-ims_ims-network:
    driver: bridge

volumes:
  backend-ims_db_app_ims:
