apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  spring.datasource.username: cm9vdA==
  spring.datasource.password: cGFzc3dvcmQ=
  spring.mail.password: cnN4dnF6bHJreWh1cXh3dg==
