apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.adminerPort }}
    targetPort: {{ .Values.service.adminerPort }}
    nodePort: {{ .Values.service.adminernodePort }}
  selector:
    app: adminer