apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.backendPort }}
    targetPort: {{ .Values.service.backendPort }}
    nodePort:  {{ .Values.service.backendnodePort }}
  selector:
    app: backend
