apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.frontendPort }}
    targetPort: {{ .Values.service.frontendPort }}
    nodePort: {{ .Values.service.frontendnodePort }}
  selector:
    app: frontend
