replicaCount: 1

image:
  backend:
    repository: wajdiraouafi/backend-ims
    tag: k8s-v4
    pullPolicy: IfNotPresent
  frontend:
    repository: wajdiraouafi/frontend-ims
    tag: k8s-v3
    pullPolicy: IfNotPresent

mysql:
  image: mysql:latest
  rootPassword: password
  database: Internship-Management-System

adminer:
  image: adminer
  port: 8080

service:
  type: NodePort
  backendPort: 8085
  frontendPort: 4200
  adminerPort: 8080
  backendNodePort: 30101
  frontendNodePort: 30100
  adminerNodePort: 30200

config:
  spring:
    datasource:
      url: jdbc:mysql://mysql-svc:3306/Internship-Management-System?useSSL=false&allowPublicKeyRetrieval=true
    mail:
      host: smtp.gmail.com
      port: "587"
      username: raowajdi@gmail.com
      properties:
        mail:
          smtp:
            auth: "true"
            starttls:
              enable: "true"
  IMS:
    app:
      jwtSecret: IMSSecretKey
      jwtExpirationMs: "3600000"
      jwtRefreshExpirationMs: "86400000"
  API_URL_auth: "http://192.168.49.2:30101/api/auth/"
  API_URL_Off: "http://192.168.49.2:30101/api/Offre/"
  API_URL_Cand: "http://192.168.49.2:30101/api/Candidature/"
